[tool.poetry]
name = "folding-cli"
version = "0.1.0"
description = ""
authors = ["AchilleSoulieID <a.soulie@instadeep.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
