name: Release new version

on:
  push:
    branches:
      - main

jobs:

  changed-files:
    name: "📂 Get changed files"
    outputs:
      cli: ${{ steps.changed-files.outputs.cli_any_changed == 'true' }}
      database: ${{ steps.changed-files.outputs.database_any_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get relevant files changed per group
        id: changed-files
        uses: tj-actions/changed-files@v44.5.0
        with:
          files_yaml: |
            cli:
              - 'folding-cli/**/*'
            database:
              - 'folding-database/**/*'

  release-database:
    if: needs.changed-files.outputs.database == 'true'
    needs: changed-files
    runs-on: ubuntu-latest
    concurrency: release
    name: "Bump version and create changelog with commitizen"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          directory: ./folding-database
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # release-cli:
  #   if: needs.changed-files.outputs.cli == 'true'
  #   needs: changed-files
  #   runs-on: ubuntu-latest
  #   concurrency: release
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Release folding-cli
  #       uses: python-semantic-release/python-semantic-release@v9.9.0
  #       with:
  #         directory: ./folding-cli
  #         github_token: ${{ secrets.GIT_TOKEN }}
